### ISSUE TITLE
Not clear what your script does

### ISSUE THREAD

**Issue by buhtz** [macro6461/changelog-python#1]
Dear Matt,
I found your script via your blog post.

I am not sure what your script really does. Where does the content for the CHANGLOG comes from? Does your script read the last git commits or something like that?

Sorry, I don't get it. Maybe you could add an example with input and output data in your README.md.

Kind
Christian

**Comment by macro6461** [comment]
@Codeberg-AsGithubAlternative-buhtz, 

The script is meant to create a CHANGELOG item (or a CHANGELOG file if one does not already exist) that is line with the current version of your app/project and also includes the date. I go over it in the [blog post](https://betterprogramming.pub/how-to-write-a-python-script-to-create-and-update-a-changelog-c2d39615064b) and mention the benefits in the README.md. It does not include git commits or git history like some other CHANGELOG generators do.

Thanks!

**Comment by macro6461** [comment]
@Codeberg-AsGithubAlternative-buhtz,

The script is meant to create a CHANGELOG item (or a CHANGELOG file if one does not already exist) that is line with the current version of your app/project and also includes the date. I go over it in the [blog post](https://betterprogramming.pub/how-to-write-a-python-script-to-create-and-update-a-changelog-c2d39615064b) and mention the benefits in the README.md. It does not include git commits or git history like some other CHANGELOG generators do.

Thanks!

**Comment by buhtz** [comment]
But it is not clear (for me) where does the "CHANGELOG item" comes from.

**Comment by macro6461** [comment]
@Codeberg-AsGithubAlternative-buhtz when I say "CHANGELOG item" I am referring to each portion of the CHANGELOG that pertains to a version number (seen as something like `[1.2.3]`) and a date (seen as something like `(2022-04-19)`). 

In `changelog.py`, the `item` is instantiated at the top with the version and today's date. In the function `new_changelog_item` is where that `item` variable is inserted at the correct line in the CHANGELOG file.

If you clone the repo and follow the README you should be able to create a changelog and add items to it depending on the version number. I used a dummy version as a variable but if you're git tagging your project commits you can access that version and use that by uncommenting out line 8 and using that instead of the dummy version I provided.

Please let me know if you need anything else!

**Comment by buhtz** [comment]
I strongly suggest to improve your README.md because "sit back while a Changelog is created or new changelog item is added" doesn't help. It would help if you could describe the workflow from modifying code, commiting it, doing your changelog.py magic and then release the package. How can your script help?

I found this comment in your code.
https://github.com/macro6461/changelog-python/blob/687861610ece63f0bd677d31178956fa81aec84e/changelog.py#L8

Am I right that the content/items for the CHANGELOG are generated from git commit messages?
But I have to extract the commit messages myself and put them into your script?

**Comment by macro6461** [comment]
@Codeberg-AsGithubAlternative-buhtz 

Yes, as I said, line 8 is if you want to use the tagged version as the current version number. You can uncomment it out and use it instead of the dummy version number provided. If someone wants to use something other than the placeholder provided or a git tagged version number I leave it up to them. 

I've mentioned in the README and the blog post that I do not use the git commit messages or any log dumps. You add the CHANGELOG comments yourself. This is intentional.

Again, as it says in the README and the blog post, the script is meant to allow the user to add a CHANGELOG item or create a new CHANGELOG if one does not exist. The script helps take care of file creation and item addition (again, minus the comments) when the script is run. It's meant to offer design/message flexibility and save you from having to type out each item and create your own file. I'm not sure how to be more clear. 

If you'd rather use a generator that generates a CHANGELOG from git logs then you'd probably prefer using something else.

**Comment by buhtz** [comment]
Then it is not a CHANGELOG generator but more an "editor", right?

**Comment by macro6461** [comment]
@Codeberg-AsGithubAlternative-buhtz 

By running the script it automatically either adds a CHANGELOG item for you to an existing CHANGELOG or it can instantiate the file itself if it doesn't exist. There's no interaction with the script beyond running the shell file. It generates a CHANGELOG or CHANGELOG item and allows you flexibility with messages and design. You can rationalize what it should be called however you want. 

Again, you're under no obligation to use this script.

**Comment by buhtz** [comment]
No offense. It wasn't about the quality and need of your script.
I just tried to understand what it is intended for and I gave hints to improve your documentation. If it works for you and supports your workflow, fine.
I also appreciate that you share your own work here.

Just keep in mind that your script is a bit "unusual" in the context of CHANGELOG helpers and because of that you should give a bit more details in your documentation to make sure the users are not misdirected because of their assumptions about "usual" tools in that context.

**Comment by macro6461** [comment]
None taken. I can keep that in mind!
